### ISSUE TITLE
[BUG] Bows and crossbows does not have stats

### ISSUE THREAD

**Issue by V1lo4ka** [MrSypz/Crital#10]
**Minecraft Version**
--1.21--

**Mod Loader Version**
--0.15.11 fabric--

**Mod Version**
--0.7.0-0.7.1--

**Screenshots/Videos**
--paste your videos/screenshots--

**Description**
--After update bows and cross bows became ones without crit stats and stars--

**Logs**
 --Log--

**Comment by diefegneig** [comment]
I would like to see other tools added, like axes or pickaxes.

**Comment by MasterZeeVII** [comment]
it now configable depend on user
file path in config/crital/crital_item_data.json
```
"minecraft:netherite_helmet": { <----- name
      "itemId": "minecraft:netherite_helmet", <--------itemId
      "baseCritChance": 7.0,
      "baseCritDamage": 7.5,
      "minCritChanceMultiply": 0.2,
      "maxCritChanceMultiply": 1.25,
      "minCritDamageMultiply": 0.7,
      "maxCritDamageMultiply": 1.5
    },
```
replace itemId and name to match minecraft one it now 
adjust as you like

**Comment by MasterZeeVII** [comment]
hold on I think I should put at least vanilla item

**Comment by MasterZeeVII** [comment]
https://modrinth.com/mod/crital/version/5QAxPcJW
ok I already set a prebuild data
delete the old config and lunch the game is good to go
if you play on server don't forgot to delete on serverside too if data exist it not gonna override

**Comment by makumaku1974** [comment]
> it now configable depend on user file path in config/crital/crital_item_data.json
> 
> ```
> "minecraft:netherite_helmet": { <----- name
>       "itemId": "minecraft:netherite_helmet", <--------itemId
>       "baseCritChance": 7.0,
>       "baseCritDamage": 7.5,
>       "minCritChanceMultiply": 0.2,
>       "maxCritChanceMultiply": 1.25,
>       "minCritDamageMultiply": 0.7,
>       "maxCritDamageMultiply": 1.5
>     },
> ```
> 
> replace itemId and name to match minecraft one it now adjust as you like

does this support any modded items becoz I would like to try...

**Comment by MasterZeeVII** [comment]
> > it now configable depend on user file path in config/crital/crital_item_data.json
> > ```
> > "minecraft:netherite_helmet": { <----- name
> >       "itemId": "minecraft:netherite_helmet", <--------itemId
> >       "baseCritChance": 7.0,
> >       "baseCritDamage": 7.5,
> >       "minCritChanceMultiply": 0.2,
> >       "maxCritChanceMultiply": 1.25,
> >       "minCritDamageMultiply": 0.7,
> >       "maxCritDamageMultiply": 1.5
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > replace itemId and name to match minecraft one it now adjust as you like
> 
> does this support any modded items becoz I would like to try...

yes it now dynamic

**Comment by diefegneig** [comment]
I wish other tools like axes and pickaxes would have effects like faster block mining or something else as their tiers increase.

**Comment by MasterZeeVII** [comment]
> I wish other tools like axes and pickaxes would have effects like faster block mining or something else as their tiers increase. I wish the tools had different effects

create a new issue and write your detail
