### ISSUE TITLE
[BUG] 1.21, Swords have no stats?

### ISSUE THREAD

**Issue by DZ10101** [MrSypz/Crital#13]
**Minecraft Version**
1.21

**Mod Loader Version**
Fabric 0.16.0

**Mod Version**
0.7.2-beta

**Screenshots/Videos**
![2024-07-21_12 04 53](https://github.com/user-attachments/assets/06d14281-09d1-4953-bf29-a3ed1a7d3955)
![2024-07-21_12 04 54](https://github.com/user-attachments/assets/2fb9242d-d98e-4e3f-a6b6-23cc2343c39d)
![2024-07-21_12 04 55](https://github.com/user-attachments/assets/eca3212f-88cd-4f5a-92b6-03485216023e)
![2024-07-21_12 04 56](https://github.com/user-attachments/assets/a31c80f9-410d-4581-b16f-593790fd9b70)
![2024-07-21_12 04 57](https://github.com/user-attachments/assets/b01727c1-717b-4e59-b4e5-253d6ab1de6c)
![2024-07-21_12 04 57_2](https://github.com/user-attachments/assets/a264e990-75e3-41f6-b5ed-2a7b52a12f17)

**Description**
I looked through the config and found no data for swords, I don't know if this is a bug or not but thought I should report it. Log is from a simple pack I made to test this and make sure there was actually no data for Swords.

**Logs**
[latest.log](https://github.com/user-attachments/files/16325382/latest.log)

**Comment by MasterZeeVII** [comment]
have grind it yet?

**Comment by MasterZeeVII** [comment]
oh I miss the sword my bad

**Comment by MasterZeeVII** [comment]
https://modrinth.com/mod/crital/version/0.7.2a-beta
fix version

**Comment by DZ10101** [comment]
Thanks!

**Comment by DZ10101** [comment]
Problem fixed! 

If it doesn't get fixed, whoever sees this, reset your config file.
