### ISSUE TITLE
[Crashing] Crital Crashes with Sassot 1.21

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Crital#3]
Somehow the mixins is complicated and im sure it crashes with this mod.

**Comment by makumaku1974** [comment]
https://mclo.gs/ZUlLwKl log:

**Comment by MasterZeeVII** [comment]
ohh mixin conflic maybe I'll override my mixin instead of sassot mixin

**Comment by MasterZeeVII** [comment]
maybe next week for update I'm make it compile with penomior too for qol stats when open inventory

**Comment by makumaku1974** [comment]
Your mods are so goated at this point. I'll be waiting anytime to test both of your mods.

**Comment by MasterZeeVII** [comment]
Ok, It now fix I'm gonna implement some QOL to this mod now like command to test stuff same as penomior
