### ISSUE TITLE
game crashes on startup

### ISSUE THREAD

**Issue by Mr-Squid42** [MrSypz/Crital#4]
https://gist.github.com/Mr-Squid42/a9b1c9013f170f49268ff345ba12ac94

**Comment by MasterZeeVII** [comment]
have try to launch the game without this mod? Seem it not problem from this mod

**Comment by Mr-Squid42** [comment]
This crash report is what i get when i try the latest version of crital, however if i downgrade to the previous version for 1,21, minecraft works

**Comment by MasterZeeVII** [comment]
> This crash report is what i get when i try the latest version of crital, however if i downgrade to the previous version for 1,21, minecraft works

maybe it not compatible with other mod try to install only crital

**Comment by Mr-Squid42** [comment]
crash report with only crital and required dependencies:
https://gist.github.com/Mr-Squid42/5c135dc49ec8523cbbe5a96fd2213bb5

**Comment by MasterZeeVII** [comment]
> crash report with only crital and required dependencies: https://gist.github.com/Mr-Squid42/5c135dc49ec8523cbbe5a96fd2213bb5

Oh I see now I forgot to change dependencies mybad

**Comment by MasterZeeVII** [comment]
ok it now fix in version 0.7.0
