### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'crital'!

### ISSUE THREAD

**Issue by diefegneig** [MrSypz/Crital#5]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'crital'!

**Comment by MrSypz** [comment]
It dependency from penomior I forgot to change before build a file

**Comment by MrSypz** [comment]
ok it now fix in version 0.7.0
