### ISSUE TITLE
1.21 Does the Crital on Tools, Weapons, and Armor from loot chest lowered?

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Crital#7]
I've tested this earlier with the dungeons and somehow Crital enhancement weapons are seemingly less in vanilla and modded. Was this in the previous update log because i cant seem to find any in modrinth.

**Comment by MasterZeeVII** [comment]
it now base on user config I'm only pre-build with sword and armor only

**Comment by makumaku1974** [comment]
i see i see.

**Comment by MasterZeeVII** [comment]
> i see i see.
#10 I already update with data build-in
