### ISSUE TITLE
Crashma Game 1.21 

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Crital#9]
https://mclo.gs/2pRwLhP

Something to do with Creative Tab 

I have both latest Penomior 0.1.6 and Crital 0.7.1

**Comment by MasterZeeVII** [comment]
I already test it with only 2 mod and nothing crash

**Comment by makumaku1974** [comment]
> I already test it with only 2 mod and nothing crash

did you find the culprit? pleease let this open for now since im redoing the modpack
